/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
import ExchangeDemoABI from "./ExchangeDemo.json";

const deployedContracts = {
  888: {
    ExchangeDemo: {
      address: "0x2fEc4a9029DFB413465a55Af45242b2548257BDA",
      abi: ExchangeDemoABI.abi,
    },
  },
};

export default deployedContracts satisfies GenericContractsDeclaration;
